### ISSUE TITLE
Missions with multiple rewards show incorrect text

### ISSUE THREAD

**Issue by janeylicious** [TekNoLogic/MissionUnpossible#5]
Screenshot is self explanatory, I think. Sorry this isn't a pull request, tekkub, I'm zoning out because of bronchitis.

![mission](https://cloud.githubusercontent.com/assets/6385/5573197/dcf2a710-8f5d-11e4-9a79-5252347f55d1.png)

**Comment by tekkub** [comment]
Yup, ran into this one myself the other day and fixed it, let me push that up.
